#server.port=8081
#spring.main.allow-bean-definition-overriding=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
##db.hibernate.dialect=org.hibernate.dialect.MySQLDialect
##db.hibernate.show_sql=true
##db.hibernate.hbm2ddl.auto=create
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/online_store?serverTimezone=UTC
    username: root
    password: Java1234
---
logging:
  level:
    root: info
  file:
    path: logs
#  pattern:
#    console: